version: '3.7'

services:
  db_dev:
    image: postgres:11.5
    env_file:
      - dev.env
    volumes:
      - ./volumes/db/pg-data_dev:/var/lib/postgresql/data
    ports:
      - 5432:5432 

  web_dev:
    depends_on:
      - db_dev
    build:
      args:
        ENV_TYPE: DEV
      context: ./
      dockerfile: Dockerfile
    env_file:
      - dev.env
    volumes:
      - ./src:/code 
      - ./volumes/web:/code/mounted
    expose:
      - 8000
    ports:
      - 8000:8000 
    command: ["./wait-for-it.sh", "db_dev:5432", "--", "./start.sh"]
