version: '3.7'

services:
  db:
    image: postgres:11.5
    env_file:
      - prod.env
    volumes:
      - ./volumes/db/pg-data:/var/lib/postgresql/data
    ports:
      - 5432:5432 

  web:
    depends_on:
      - db
    build:
      args:
        ENV_TYPE: PROD
      context: ./
      dockerfile: Dockerfile
    env_file:
      - prod.env
    volumes:
      - ./volumes/web:/code/mounted
    expose:
      - 8001
    command: ["./wait-for-it.sh", "db:5432", "--", "./start.sh"]

  nginx:
    depends_on:
      - web
    build: ./nginx
    volumes:
      - ./volumes/web/static:/code/handwriting/static
    ports:
      - 80:80
