# Generated by Django 2.2.5 on 2019-09-28 10:48

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import handwriting.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawInputData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=1)),
                ('image_data', handwriting.models.NumpyArrayField(base_field=models.FloatField(), size=None)),
                ('original_image_dimmensions', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=None, null=True, size=None)),
                ('bounding_box', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=None, null=True, size=None)),
                ('insertion_date', models.DateTimeField(verbose_name='date inserted')),
                ('ip_address', models.GenericIPAddressField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_data', handwriting.models.NumpyArrayField(base_field=models.FloatField(), size=None)),
                ('resized_image_dimmensions', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=None, null=True, size=None)),
                ('rotation_angle', models.IntegerField()),
                ('raw_input_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handwriting.RawInputData')),
            ],
        ),
    ]
