# Generated by Django 2.2.5 on 2019-09-28 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handwriting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawinputdata',
            name='discarded',
            field=models.BooleanField(default=False),
        ),
    ]
