# Generated by Django 2.2.5 on 2019-09-29 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handwriting', '0002_rawinputdata_discarded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='raw_input_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='handwriting.RawInputData'),
        ),
    ]
